export type UserCreate =  {
    id:number
    email:string
    firstName:string
    lastName:string
    userStatusId:number
    userTypeId:number
    phone:number
    instagram:string
    positionId:string
    updatedAt:string
    createdAt:string
    membershipId:string
    address:string
    client:string
    company:string
    Contract:string
    Project:string
    membership:string
    position:string
    userStatus:string
    userType:string
}